### ISSUE TITLE
Dataset labels

### ISSUE THREAD

**Issue by baizhongyu** [umfieldrobotics/ai4shipwrecks-scripts#1]
Thank you for your contributions to this field. But the labels in the data set are all black pictures. I hope the problem can be solved as soon as possible. Thanks again.

**Comment by anja-sheppard** [comment]
Hi, thanks for your interest! The labels are composed of pixels that represent the binary classes with values `0`(other) and `1` (shipwreck), so they will appear black to the viewer. You're welcome to open the images in python and multiply the pixel values by 255 to see the labels more clearly.
